name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jupyter:latest
  deploy:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4
    - name: Push the Docker image
      run: docker push jupyter:latest

